### ISSUE TITLE
How do I install afloat?

### ISSUE THREAD

**Issue by Sanabria** [millenomi/afloat#6]
Hey guys,

I was using the former installer supplied by the developer on his site but now I have no idea how to install it from the zip I downloaded from github.

Pretty sure it's easy but I'd appreciate if somebody could point me in the right direction.

Thanks.

**Comment by bored-engineer** [comment]
run `xcodebuild -configuration Release install` then reboot should work.

**Comment by millenomi** [comment]
Please do not install Afloat if you don't know what you're doing. (The install action works?!? whoa, good job configuring the project, Past Me.)

I purposefully removed the public page and build because I do not have the time to fix anything that may break Afloat in the future. By only providing the source, I make sure that only people with a decent experience fixing source problems can make it work — so if something goes wrong, they can fix it for themselves (and possibly fork it and make the fix available on GitHub).

I don't have the bandwidth to keep doing my day job _and_ fix Afloat to, say, adapt to whatever quirk Mavericks or Application XYZ may introduce. And I don't want old builds laying around, triggering any aforementioned quirks to the frustration of potentially update-demanding users. So, until I can actually devote the time to make proper, supported releases, Afloat is available in source form only from me.

Sorry, ∞

**Comment by bored-engineer** [comment]
Update: Install does not seem to actually work. The proper method is to copy the resulting afloat.bundle from build/Release to the SIMBL plugin directory.

**Comment by millenomi** [comment]
Oh, Past Me screwed up. Ew.

Well, see above.
